version: 2

jobs:
    build:

# The deployment section should be excluded until
# it is explicitly included in module 5

#deployment:
#  dockerhub:
#    branch: master
#    commands:
#      - $DOCKER_HUB_TRIGGER

steps:
        - checkout
        - run:
			
test:
  override:    
     - mocha